### ISSUE TITLE
Updates not applying

### ISSUE THREAD

**Issue by iridian-ks** [pulumi/pulumi-consul#31]
Hello,

I'm new to Pulumi so I apologize if I'm simply doing something wrong. I noticed that when I updated service checks that Pulumi is SEEING the updates but not APPLYING them.

Here's some of the output.

```
     ├─ consul:index:Service  n04-ssh                                        [diff: -address,datacenter,meta,serviceId,tags~checks]
     ├─ consul:index:Service  n03-ssh                                     [diff: -address,datacenter,meta,serviceId,tags~checks]
     ├─ consul:index:Service  n03-node_exporter                           [diff: -address,datacenter,meta,serviceId~checks]
     ├─ consul:index:Service  n12-process_exporter_ncabatoff              [diff: -address,datacenter,meta,serviceId~checks]
 ~   ├─ consul:index:Service n03-node_exporter                 updated     [diff: ~checks]
 ~   ├─ consul:index:Service  n03-ssh                           updated     [diff: ~checks]
 ~   ├─ consul:index:Service  n02-node_exporter                  updated     [diff: ~checks]
 ~   ├─ consul:index:Service n03-node_exporter                 updated     [diff: ~checks]
     ├─ consul:index:Service n03-process_exporter_ncabatoff              [diff: -address,datacenter,meta,serviceId~checks]
```

The tilde's show what is actually getting updated and the resources not getting updated also have a tilde next to checks, but the resource itself isn't getting the change. I looked through the CLI to see if there's a way to force updates, but I'm not seeing anything.

Any help is appreciated! :)

**Comment by leezen** [comment]
Is this from a `preview` diff? In some cases, the preview is overly conservative on what will get updated (such as not knowing if an output will change and cause downstream changes). But, during actual `update` time, it turns out those outputs don't change and so the subsequent updates don't need to happen.

**Comment by iwahbe** [comment]
It's been a while 😄. If this is still a problem for you, please open another issue. Otherwise I'm closing.
