### ISSUE TITLE
Package broken because require('license') is in index

### ISSUE THREAD

**Issue by madmod** [pulumi/pulumi-consul#71]
The license file is loaded using `__export(require('./license'))` on line 44 of `index.js` which breaks the package.

## Expected behavior

The package should work. 😄 

## Steps to reproduce

1. npm i @pulumi/consul
2. add `import * as consul from '@pulumi/consul'
3. run
4.

## Context (Environment)

Typescript with node 15.5.1

**Comment by leezen** [comment]
@stack72 Seems like somehow the actual `LICENSE` file ends up in the packaged up directory, leading the module import to try loading that file instead of the `license.js` that's actually there.
